apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  account-balance-service
  name:  account-balance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  account-balance-service
  template:
    metadata:
      labels:
        name:  account-balance-service
    spec:
      containers:
        - env:
            - name: spring.application.name
              value: account-balance-service
            - name: server.port
              value: "8080"
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: spring_rabbitmq_username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: spring.profiles.active
              value: "valKey"
            - name: spring.data.redis.host
              value: "valkey-master"
            - name: spring.data.redis.password
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: valkey-password
            - name: spring.data.redis.client-name
              value: "account-balance-service"
          image: cloudnativedata/account-balance-service:0.0.1-SNAPSHOT
          name: account-balance-service
          imagePullPolicy: Always
#          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: account-balance-service
spec:
  selector:
    name: account-balance-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer