apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  payment-service
  name:  payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  payment-service
  template:
    metadata:
      labels:
        name:  payment-service
    spec:
      containers:
        - env:
            - name: spring.application.name
              value: payment-service
            - name: server.port
              value: "8081"
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: spring_rabbitmq_username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: spring.profiles.active
              value: "valKey"
            - name: spring.data.redis.host
              value: "valkey-master"
            - name: spring.data.redis.password
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: valkey-password
            - name: spring.data.redis.client-name
              value: "payment-service"
          image: cloudnativedata/payment-service:0.0.1-SNAPSHOT
          name: payment-service
#          imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    name: payment-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer