spring:
  application:
      name: account-balance
  cloud:
    function:
      definition: readBalanceFunction;paymentConsumer
    stream:
      bindings:
        readBalanceFunction-in-0:
          destination: readBalance
          group: ${spring.application.name}
        readBalanceFunction-out-0:
          destination: balance
        paymentConsumer-in-0:
         destination: payment
         group: ${spring.application.name}
      http:
        GET: readBalanceFunction
        POST: paymentConsumer
      rabbit:
        bindings:
          paymentConsumer-in-0:
            consumer:
              quorum.enabled: true
          readBalanceFunction-in-0:
            consumer:
              quorum.enabled: true
      binder:
        connection-name-prefix: "account-balance"